## Explolatory Data Analysis

### Understand The Problem Statement

Financial Inclusion remains one of the main obstacles to economic and human development in Africa. For example, across Kenya, Rwanda, Tanzania, and Uganda only 9.1 million adults (or 13.9% of the adult population) have access to or use a commercial bank account.

Traditionally, access to bank accounts has been regarded as an indicator of financial inclusion. Despite the proliferation of mobile money in Africa, and the growth of innovative fintech solutions, banks still play a pivotal role in facilitating access to financial services. Access to bank accounts enable households to save and facilitate payments while also helping businesses build up their credit-worthiness and improve their access to other finance services. Therefore, access to bank accounts is an essential contributor to long-term economic growth.

The objective of this Dataset is to create a machine learning model to predict which individuals are most likely to have or use a bank account. The models and solutions developed can provide an indication of the state of financial inclusion in Kenya, Rwanda, Tanzania and Uganda, while providing insights into some of the key demographic factors that might drive individuals’ financial outcomes.

Data source available in the the zindi platform, [Zindi Africa](https://zindi.africa/competitions/financial-inclusion-in-africa)

### Type of the Problem
It is a classification problem where we have to predict whether individuals are most likely to have or use a bank account or not.In a classification problem, we have to predict discrete values based on a given set of independent variable.

### Hypothesis Generation
This is a very important stage in any data science/machine learning pipeline. It involves understanding the problem in detail by brainstorming as many factors as possible which can impact the outcome. It is done by understanding the problem statement thoroughly and before looking at the data.

Below are some of the factors which I think can affect the chance for a person to have a bank account

- People who have mobile phone have lower chance to use bank account because of mobile money services.
- People who are employed have a higher chance of having a bank account than People who are unemployed.
- people with low education have low chance to have bank account
- people in rural areas have low chance to have bank account 
- people who have age below 18 have low chance to have bank account
- female have less chance to have bank account



### Load Python Packages

In [2]:
# import important modules 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
plt.rcParams["axes.labelsize"] = 18
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline 


## Load Dataset

In [3]:
# Import data
data = pd.read_csv('../data/financial_inclusion.csv')



In [4]:
# print shape 
print('train data shape :', data.shape)

train data shape : (23524, 13)


The above output show the number of rows and columns for dataset 

In [11]:
# Inspect Data by shing the first five rows 
data.head()

country  year    uniqueid bank_account location_type cellphone_access  \
0   Kenya  2018  uniqueid_1          Yes         Rural              Yes   
1   Kenya  2018  uniqueid_2           No         Rural               No   
2   Kenya  2018  uniqueid_3          Yes         Urban              Yes   
3   Kenya  2018  uniqueid_4           No         Rural              Yes   
4   Kenya  2018  uniqueid_5           No         Urban               No   

   household_size  age_of_respondent gender_of_respondent  \
0               3                 24               Female   
1               5                 70               Female   
2               5                 26                 Male   
3               5                 34               Female   
4               8                 26                 Male   

  relationship_with_head           marital_status  \
0                 Spouse  Married/Living together   
1      Head of Household                  Widowed   
2         Other relative     Single/Never Married   
3      Head of Household  Married/Living together   
4                  Child     Single/Never Married   

                   education_level                   job_type  
0              Secondary education              Self employed  
1              No formal education       Government Dependent  
2  Vocational/Specialised training              Self employed  
3                Primary education  Formally employed Private  
4                Primary education        Informally employed

**Note:** Open the VariableDefinition file to understand the meaning of each variable in this dataset 

### Explolatory Data Analysis 

This is the process of finding some insights from you dataset before create predictive models.

**Note:** This is important steps in your Data science workflow.

In [12]:
#show list of columns 
list(data.columns)  

['country',
 'year',
 'uniqueid',
 'bank_account',
 'location_type',
 'cellphone_access',
 'household_size',
 'age_of_respondent',
 'gender_of_respondent',
 'relationship_with_head',
 'marital_status',
 'education_level',
 'job_type']

In [13]:
## show Some information about the dataset 
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
country                   23524 non-null object
year                      23524 non-null int64
uniqueid                  23524 non-null object
bank_account              23524 non-null object
location_type             23524 non-null object
cellphone_access          23524 non-null object
household_size            23524 non-null int64
age_of_respondent         23524 non-null int64
gender_of_respondent      23524 non-null object
relationship_with_head    23524 non-null object
marital_status            23524 non-null object
education_level           23524 non-null object
job_type                  23524 non-null object
dtypes: int64(3), object(10)
memory usage: 2.3+ MB
None


The outshow shows the list of variables , sizes and data types in each variables. This will help you to know what feature engineering you can apply.

In [14]:
# Check for missing values
print('missing values:', data.isnull().sum())

missing values: country                   0
year                      0
uniqueid                  0
bank_account              0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64


We don't have missing data in our dataset.

### A.Univariate Analysis

In this section, we will do univariate analysis. It is the simplest form of analyzing data where we examine each variable individually. For categorical features we can use frequency table or bar plots which will calculate the number of each category in a particular variable. For numerical features, probability density plots can be used to look at the distribution of the variable.

In [15]:
# Frequency table of a variable will give us the count of each category in that Target variable.
data['bank_account'].value_counts() 

No     20212
Yes     3312
Name: bank_account, dtype: int64

In [16]:
# Explore Target distribution 

sns.catplot(x="bank_account", kind="count", data= data)

The data shows that we have large number of **no** class than **yes** class  in our target variable 

In [17]:
# Explore Country distribution 

sns.catplot(x="country", kind="count", data=data)

Most of the data where collected in Rwanda and less data collected in Uganda 

In [18]:
# Explore Location distribution 

sns.catplot(x="location_type", kind="count", data=data)

Most people live in rural area than urban area 

In [19]:
# Explore Years distribution 

sns.catplot(x="year", kind="count", data=data)

Most of the data were collected in 2016 

In [20]:
# Explore cellphone_access distribution 

sns.catplot(x="cellphone_access", kind="count", data=data)

Most of the particiapants have access to the cellphone 

In [21]:
# Explore gender_of_respondents distribution 

sns.catplot(x="gender_of_respondent", kind="count", data=data)

We have more Females than Males 

In [26]:

# Explore relationship_with_head distribution 

sns.catplot(x="relationship_with_head", kind="count", data=data);

plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4, 5]), <a list of 6 Text xticklabel objects>)

We have more head of Household particants and few other non-relatives 

In [25]:

# Explore marital_status  distribution 

sns.catplot(x="marital_status", kind="count", data=data);

plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4]), <a list of 5 Text xticklabel objects>)

Most of the participants are maried/living together

In [27]:
# Explore education_level  distribution 

sns.catplot(x="education_level", kind="count", data=data); 

plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4, 5]), <a list of 6 Text xticklabel objects>)

Most of the participants have primary education level 

In [28]:
# Explore job_type distribution 


sns.catplot(x="job_type", kind="count", data=data); 

plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
) 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), <a list of 10 Text xticklabel objects>)

Most of the participants are self employed

In [32]:

# Explore household_size distribution 

plt.figure(figsize=(16, 6))
data.household_size.hist() 
plt.xlabel('Household  size')

Text(0.5, 0, 'Household  size')

Household_size is not normally distributed and the most common number of people living in the house is 2 

In [33]:
# Explore age_of_respondent distribution 
plt.figure(figsize=(16, 6))
data.age_of_respondent.hist() 
plt.xlabel('Age of Respondent')

Text(0.5, 0, 'Age of Respondent')

most of the participant's age is between 25 and 35 

### B.Bivariate Analysis

Bivariate analysis is the simultaneous analysis of two variables (attributes). It explores the concept of relationship between two variables, whether there exists an association and the strength of this association, or whether there are differences between two variables and the significance of these differences.

After looking at every variable individually in univariate analysis, we will now explore them again with respect to the target variable.

In [35]:
#Explore location type  vs bank account 

plt.figure(figsize=(16, 6))
sns.countplot('location_type', hue= 'bank_account', data=data)
plt.xticks(
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1]), <a list of 2 Text xticklabel objects>)

In [36]:
#Explore gender_of_respondent vs bank account 
plt.figure(figsize=(16, 6))
sns.countplot('gender_of_respondent', hue= 'bank_account', data=data)
plt.xticks(
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1]), <a list of 2 Text xticklabel objects>)

In [23]:
#Explore cellphone_accesst vs bank account 
plt.figure(figsize=(16, 6))
sns.countplot('cellphone_access', hue= 'bank_account', data=data)
plt.xticks(
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1]), <a list of 2 Text xticklabel objects>)

In [37]:
#Explore relationship_with_head vs bank account 

plt.figure(figsize=(16, 6))
sns.countplot('relationship_with_head', hue= 'bank_account', data=data)
plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4, 5]), <a list of 6 Text xticklabel objects>)

In [38]:
#Explore 'marital_status vs bank account 

plt.figure(figsize=(16, 6))
sns.countplot('marital_status', hue= 'bank_account', data=data)
plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4]), <a list of 5 Text xticklabel objects>)

In [39]:
#Explore 'education_level vs bank account 

plt.figure(figsize=(16, 6))
sns.countplot('education_level', hue= 'bank_account', data=data)
plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4, 5]), <a list of 6 Text xticklabel objects>)

In [40]:
#Explore job_type vs bank account 

plt.figure(figsize=(16, 6))
sns.countplot('job_type', hue= 'bank_account', data=data)
plt.xticks(
    rotation=45, 
    horizontalalignment='right',
    fontweight='light',
    fontsize='x-large'  
)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), <a list of 10 Text xticklabel objects>)

### Our Hypothesis Results

- People who have mobile phone have lower chance to use bank account because of mobile money services.-TRUE
- People who are employed have a higher chance of having a bank account than People who are unemployed. -TRUE
- people with low education have low chance to have bank account - TRUE
- people in rural areas have low chance to have bank account -TRUE
- people who have age below 18 have low chance to have bank account-TRUE
- female have less chance to have bank account -TRUE

### DATA PROFILING PACKAGE 